/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Quest } from "./Quest";
import { QuestCountArgs } from "./QuestCountArgs";
import { QuestFindManyArgs } from "./QuestFindManyArgs";
import { QuestFindUniqueArgs } from "./QuestFindUniqueArgs";
import { DeleteQuestArgs } from "./DeleteQuestArgs";
import { QuestService } from "../quest.service";
@graphql.Resolver(() => Quest)
export class QuestResolverBase {
  constructor(protected readonly service: QuestService) {}

  async _questsMeta(
    @graphql.Args() args: QuestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Quest])
  async quests(@graphql.Args() args: QuestFindManyArgs): Promise<Quest[]> {
    return this.service.quests(args);
  }

  @graphql.Query(() => Quest, { nullable: true })
  async quest(
    @graphql.Args() args: QuestFindUniqueArgs
  ): Promise<Quest | null> {
    const result = await this.service.quest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Quest)
  async deleteQuest(
    @graphql.Args() args: DeleteQuestArgs
  ): Promise<Quest | null> {
    try {
      return await this.service.deleteQuest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
